<?php
/**
 * Plugin Name: Keelworks Page Snapshot Bridge
 * Plugin URI:  https://keelworks.ai/
 * Description: Adds Basic-Auth REST endpoints to take a complete, restorable snapshot of a page — raw post_content, every postmeta key (including page-builder data such as _elementor_data), the AIOSEO row and the page template — and to restore one. Core REST cannot read protected meta, so a "backup" taken without this plugin cannot rebuild a page-builder page. Only Administrators and Editors can call these routes.
 * Version:     1.1.0
 * Author:      Keelworks
 * Author URI:  https://keelworks.ai/
 * License:     MIT
 * Requires at least: 5.7
 * Requires PHP: 7.4
 *
 * Endpoints:
 *   GET  /wp-json/keelworks/v1/page-snapshot/<post_id>
 *   POST /wp-json/keelworks/v1/page-restore/<post_id>
 *
 * Auth: WordPress Basic Auth via Application Password. Caller must be an
 * Administrator or Editor (capability: edit_others_pages).
 *
 * ⚠️ The _elementor_data slash problem
 * ------------------------------------
 * Elementor stores its layout as a JSON string in postmeta. That JSON contains
 * escaped sequences, and WordPress runs wp_unslash() on meta values as they are
 * written. Restoring _elementor_data without re-applying wp_slash() strips a level
 * of escaping and produces JSON Elementor cannot parse — the page renders blank.
 * This plugin applies wp_slash() on write and verifies the round-trip before
 * reporting success. This is the single most common way an Elementor restore fails.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'KEELWORKS_SNAPSHOT_VERSION', '1.1.0' );

/**
 * Meta keys that are regenerated by the platform and are not worth restoring.
 * _elementor_css is a rebuildable cache; restoring a stale copy is worse than
 * letting Elementor regenerate it.
 */
function keelworks_snapshot_skip_meta_keys() {
	return array( '_edit_lock', '_edit_last', '_elementor_css', '_wp_old_slug' );
}

add_action( 'rest_api_init', function () {

	$permission = function () {
		return current_user_can( 'edit_others_pages' );
	};

	$id_arg = array(
		'id' => array(
			'validate_callback' => function ( $param ) {
				return is_numeric( $param ) && intval( $param ) > 0;
			},
		),
	);

	register_rest_route( 'keelworks/v1', '/page-snapshot/(?P<id>\d+)', array(
		'methods'             => 'GET',
		'callback'            => 'keelworks_snapshot_get',
		'permission_callback' => $permission,
		'args'                => $id_arg,
	) );

	register_rest_route( 'keelworks/v1', '/page-restore/(?P<id>\d+)', array(
		'methods'             => 'POST',
		'callback'            => 'keelworks_snapshot_restore',
		'permission_callback' => $permission,
		'args'                => $id_arg,
	) );

	register_rest_route( 'keelworks/v1', '/page-meta-raw/(?P<id>\d+)', array(
		'methods'             => 'POST',
		'callback'            => 'keelworks_meta_raw_write',
		'permission_callback' => $permission,
		'args'                => $id_arg,
	) );
} );

/**
 * GET — return everything needed to rebuild this page exactly.
 */
function keelworks_snapshot_get( $request ) {
	global $wpdb;

	$post_id = intval( $request['id'] );
	$post    = get_post( $post_id );

	if ( ! $post ) {
		return new WP_Error( 'keelworks_not_found', "No post with ID {$post_id}.", array( 'status' => 404 ) );
	}

	// Every meta key, including protected underscore-prefixed ones. This is the
	// part core REST will not give you, and the reason this plugin exists.
	$raw_meta = get_post_meta( $post_id );
	$skip     = keelworks_snapshot_skip_meta_keys();
	$meta     = array();

	foreach ( $raw_meta as $key => $values ) {
		if ( in_array( $key, $skip, true ) ) {
			continue;
		}
		// get_post_meta returns every value as an array; preserve multi-value keys.
		$meta[ $key ] = count( $values ) === 1 ? $values[0] : $values;
	}

	$builder = array(
		'is_elementor'    => ( get_post_meta( $post_id, '_elementor_edit_mode', true ) === 'builder' ),
		'elementor_data_bytes' => strlen( (string) get_post_meta( $post_id, '_elementor_data', true ) ),
		'elementor_version'    => get_post_meta( $post_id, '_elementor_version', true ),
		'page_template'        => get_post_meta( $post_id, '_wp_page_template', true ),
	);

	// AIOSEO row, if the plugin and its table are present.
	$aioseo = null;
	$table  = $wpdb->prefix . 'aioseo_posts';
	if ( $wpdb->get_var( $wpdb->prepare( 'SHOW TABLES LIKE %s', $table ) ) === $table ) {
		$aioseo = $wpdb->get_row(
			$wpdb->prepare( "SELECT * FROM {$table} WHERE post_id = %d", $post_id ),
			ARRAY_A
		);
	}

	$payload = array(
		'snapshot_version' => KEELWORKS_SNAPSHOT_VERSION,
		'taken_at'         => current_time( 'mysql', true ),
		'site_url'         => get_site_url(),
		'post_id'          => $post_id,
		'post'             => array(
			'post_title'     => $post->post_title,
			'post_name'      => $post->post_name,
			'post_content'   => $post->post_content,   // RAW — not the rendered filter output
			'post_excerpt'   => $post->post_excerpt,
			'post_status'    => $post->post_status,
			'post_type'      => $post->post_type,
			'post_parent'    => $post->post_parent,
			'menu_order'     => $post->menu_order,
			'comment_status' => $post->comment_status,
			'ping_status'    => $post->ping_status,
			'post_date_gmt'  => $post->post_date_gmt,
			'post_modified_gmt' => $post->post_modified_gmt,
		),
		'meta'             => $meta,
		'builder'          => $builder,
		'aioseo'           => $aioseo,
		'checksums'        => array(
			'post_content'    => md5( (string) $post->post_content ),
			'_elementor_data' => md5( (string) get_post_meta( $post_id, '_elementor_data', true ) ),
		),
	);

	return rest_ensure_response( $payload );
}

/**
 * POST — restore a page from a snapshot payload.
 *
 * Body: the snapshot object, plus:
 *   "confirm": "<post_id>"   required — guards against an accidental restore
 *   "dry_run": true          optional — report what would change, write nothing
 */
function keelworks_snapshot_restore( $request ) {
	$post_id  = intval( $request['id'] );
	$body     = $request->get_json_params();
	$dry_run  = ! empty( $body['dry_run'] );

	if ( empty( $body['post'] ) || ! isset( $body['meta'] ) ) {
		return new WP_Error( 'keelworks_bad_payload', 'Payload must contain "post" and "meta".', array( 'status' => 400 ) );
	}

	if ( ! $dry_run && ( ! isset( $body['confirm'] ) || (string) $body['confirm'] !== (string) $post_id ) ) {
		return new WP_Error(
			'keelworks_unconfirmed',
			'Refusing to restore: send "confirm" set to the post ID, or "dry_run": true.',
			array( 'status' => 400 )
		);
	}

	if ( isset( $body['post_id'] ) && intval( $body['post_id'] ) !== $post_id ) {
		return new WP_Error(
			'keelworks_id_mismatch',
			sprintf( 'Snapshot is for post %d but the route targets %d.', intval( $body['post_id'] ), $post_id ),
			array( 'status' => 400 )
		);
	}

	if ( ! get_post( $post_id ) ) {
		return new WP_Error( 'keelworks_not_found', "No post with ID {$post_id}.", array( 'status' => 404 ) );
	}

	$planned = array(
		'post_fields' => array_keys( $body['post'] ),
		'meta_keys'   => array_keys( $body['meta'] ),
	);

	if ( $dry_run ) {
		return rest_ensure_response( array( 'dry_run' => true, 'would_restore' => $planned ) );
	}

	// 1 — post fields. wp_slash() because wp_update_post expects slashed data.
	$postarr = array( 'ID' => $post_id );
	foreach ( array( 'post_title', 'post_name', 'post_content', 'post_excerpt', 'post_status', 'post_parent', 'menu_order', 'comment_status', 'ping_status' ) as $f ) {
		if ( isset( $body['post'][ $f ] ) ) {
			$postarr[ $f ] = $body['post'][ $f ];
		}
	}
	$updated = wp_update_post( wp_slash( $postarr ), true );
	if ( is_wp_error( $updated ) ) {
		return $updated;
	}

	// 2 — meta. wp_slash() is mandatory here; see the header note on _elementor_data.
	$skip    = keelworks_snapshot_skip_meta_keys();
	$written = array();
	foreach ( $body['meta'] as $key => $value ) {
		if ( in_array( $key, $skip, true ) ) {
			continue;
		}
		delete_post_meta( $post_id, $key );
		foreach ( (array) ( is_array( $value ) ? $value : array( $value ) ) as $v ) {
			add_post_meta( $post_id, $key, wp_slash( $v ) );
		}
		$written[] = $key;
	}

	// 3 — drop Elementor's generated CSS so it rebuilds from the restored data.
	delete_post_meta( $post_id, '_elementor_css' );
	if ( class_exists( '\\Elementor\\Plugin' ) ) {
		try {
			\Elementor\Plugin::$instance->files_manager->clear_cache();
		} catch ( \Throwable $e ) { // phpcs:ignore
			// Cache clearing is best-effort; a stale cache regenerates on next view.
		}
	}

	// 4 — verify the round-trip actually landed. This is what makes the restore trustworthy.
	$now_content   = get_post_field( 'post_content', $post_id );
	$now_elementor = (string) get_post_meta( $post_id, '_elementor_data', true );
	$verify = array(
		'post_content_matches'    => md5( (string) $now_content ) === ( $body['checksums']['post_content'] ?? null ),
		'_elementor_data_matches' => md5( $now_elementor ) === ( $body['checksums']['_elementor_data'] ?? null ),
		'_elementor_data_is_valid_json' => ( $now_elementor === '' ) ? null : ( json_decode( $now_elementor ) !== null ),
	);

	return rest_ensure_response( array(
		'restored'    => true,
		'post_id'     => $post_id,
		'meta_keys'   => $written,
		'verify'      => $verify,
		'all_ok'      => ( $verify['post_content_matches'] && $verify['_elementor_data_matches'] !== false ),
	) );
}

/**
 * POST — write raw meta values directly via $wpdb, bypassing maybe_serialize().
 *
 * This exists because the page-restore route (and WordPress's own update_post_meta)
 * calls maybe_serialize() on every value, which double-wraps strings that look like
 * serialized PHP data (e.g. "a:0:{}" becomes "s:6:"a:0:{}";"). Each round-trip through
 * the restore route adds one nesting layer, corrupting AIOSEO meta fields that store
 * serialized empty arrays.
 *
 * Body (JSON):
 *   {
 *     "meta": { "key": "raw_db_value", ... },
 *     "confirm": "<post_id>"
 *   }
 *
 * Each value is written to wp_postmeta.meta_value AS-IS — no wp_slash, no
 * maybe_serialize. The caller is responsible for providing the exact DB-level value.
 *
 * NOTE (2026-08-24): AIOSEO reads _aioseo_* meta from its own aioseo_posts table
 * via a get_post_metadata filter, NOT from wp_postmeta. Writing to postmeta alone
 * does not change what get_post_meta returns for these keys.
 */
function keelworks_meta_raw_write( $request ) {
	global $wpdb;

	$post_id = intval( $request['id'] );

	if ( ! get_post( $post_id ) ) {
		return new WP_Error( 'keelworks_not_found', "No post with ID {$post_id}.", array( 'status' => 404 ) );
	}

	$body = $request->get_json_params();

	if ( ! isset( $body['confirm'] ) || (string) $body['confirm'] !== (string) $post_id ) {
		return new WP_Error(
			'keelworks_unconfirmed',
			'Send "confirm" set to the post ID.',
			array( 'status' => 400 )
		);
	}

	if ( empty( $body['meta'] ) || ! is_array( $body['meta'] ) ) {
		return new WP_Error(
			'keelworks_bad_payload',
			'Payload must contain "meta" as a {key: raw_value} object.',
			array( 'status' => 400 )
		);
	}

	$table   = $wpdb->postmeta;
	$results = array();

	foreach ( $body['meta'] as $key => $raw_value ) {
		// Read before
		$before = $wpdb->get_var( $wpdb->prepare(
			"SELECT meta_value FROM {$table} WHERE post_id = %d AND meta_key = %s LIMIT 1",
			$post_id, $key
		) );

		if ( $before === null ) {
			$results[ $key ] = array( 'error' => 'meta key not found' );
			continue;
		}

		// Write raw — no maybe_serialize, no wp_slash
		$updated = $wpdb->update(
			$table,
			array( 'meta_value' => $raw_value ),
			array( 'post_id' => $post_id, 'meta_key' => $key ),
			array( '%s' ),
			array( '%d', '%s' )
		);

		// Clear the WP object cache for this post's meta so get_post_meta reads fresh
		wp_cache_delete( $post_id, 'post_meta' );

		// Read after
		$after = $wpdb->get_var( $wpdb->prepare(
			"SELECT meta_value FROM {$table} WHERE post_id = %d AND meta_key = %s LIMIT 1",
			$post_id, $key
		) );

		$results[ $key ] = array(
			'before_db' => $before,
			'after_db'  => $after,
			'match'     => ( $after === $raw_value ),
		);
	}

	return rest_ensure_response( array(
		'ok'      => true,
		'post_id' => $post_id,
		'results' => $results,
	) );
}
